## DATABASE ENV ##
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: 1998
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: emailDb
##SERVER
SERVER_PORT: 9000
ACTTIVE_PROFILES: dev
##EMAIL CONFIG
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: hamdihamza.aui@gmail.com
EMAIL_PASSWORD: yhio qfjq gqol agke
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}
